---
_hotel_id: COU151
_portal_id: required-but-empty
_root_path: https://qa5.ttaws.com/rt
latitude: 42.30648
longitude: -71.38285
name: Courtyard by Marriott Boston Natick
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 342 Speen St
  street2: ''
  state: Massachusetts
  city: Natick
  country: United States
  zip_code: '01760'
